const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE:' CHANGE_LANGUAGE',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',
      
  // gender
  FETCH_GENDER_START: 'FETCH_GENDER_START',
  FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
  FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

  // position
  FETCH_POSITION_START: 'FETCH_POSITION_START',
  FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
  FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

  // role
  FETCH_ROLE_START: 'FETCH_ROLE_START',
  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

   // save Action khi tạo user thành công
   CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',

  // edit user
  // save Action khi sửa user thành công
  SET_EDIT_USER : 'SET_EDIT_USER',
EDIT_USER_START: 'EDIT_USER_START',
EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
EDIT_USER_FAILED: 'EDIT_USER_FAILED',
   // xoa du lieu
   DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILED: 'DELETE_USER_FAILED',
  // get du lieu user ra table 
  FETCH_ALL_USERS_START : 'FETCH_ALL_USERS_START',
   FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
 // get du lieu bac di noi bat outtanding doctor
  FETCH_OUTSTANDING_DOCTORS_START: 'FETCH_OUTSTANDING_DOCTORS_START',
  FETCH_OUTSTANDING_DOCTORS_SUCCESS: 'FETCH_OUTSTANDING_DOCTORS_SUCCESS',
  FETCH_OUTSTANDING_DOCTORS_FAILED: 'FETCH_OUTSTANDING_DOCTORS_FAILED',

});



export default actionTypes;


// File/Thư mục	Vai trò chính
// actionTypes.js	Định nghĩa tên các action
// appActions.js	Viết các hàm tạo action để dispatch
// appReducer.js	Xử lý action và cập nhật state tương ứng
// rootReducer.js	Kết hợp tất cả reducer lại thành root reducer
// store	Nơi khai báo toàn bộ logic Redux của ứng dụng